### ISSUE TITLE
Brush up code.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#111]

**Comment by ghost** [comment]
https://github.com/tacigar/maidroid/blob/master/maidroid/api.lua#L521
ここ、`local`が抜けてるっぽいですね。

**Comment by tacigar** [comment]
ほんとですね....

**Comment by ghost** [comment]
https://github.com/tacigar/maidroid/blob/master/maidroid/api.lua#L530
ここはminetest.registered_itemsだけ確認すれば済みます。
エンジンの[register.lua](https://github.com/minetest/minetest/blob/master/builtin/game/register.lua)を見ていただければ分かるのですが、全部typeが違うだけのitemだったりします。

あとfarming coreのコードを見ていて思ったのですが、`minetest.registered_*`から定義を読み込む場合はnilチェックをした方が良いと思います。もしunknownノードに当たった場合エラーになるので…。

**Comment by tacigar** [comment]
>  ここはminetest.registered_itemsだけ確認すれば済みます。

たしかそんな感じだったような気もしてたんですが, 調べ直すのが面倒で全部書いてました 😞 

> `minetest.registered_*` から定義を読み込む場合はnilチェックをした方が良いと思います

ありがとうございます. 直します. 😃
