### ISSUE TITLE
0.1.0 リリースまで.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#116]
- [x] Minetest Forums で, WIP Mods から Mod Releases に移動したい.
    + そのまま移動できるのか.
    + Topic を立て直さないとダメなのか.
- [x] 0.4.15 での動作確認
- [x] タグ付け
- [x] ...

**Comment by ghost** [comment]
https://forum.minetest.net/viewtopic.php?t=10418
Releasesへの移動はここで依頼できます。

**Comment by tacigar** [comment]
ありがとうございます！
