### ISSUE TITLE
ライセンスについて.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#117]
ぶっちゃけどうでもいいが, WTFPL が割と多くを占めてるっぽい Minetest 界隈において, GPL は厳しすぎる感がある.

**Comment by tacigar** [comment]
LGPLv2.1+ が推奨されてるっぽいので, そうすることにする.

**Comment by ghost** [comment]
GPLv3を使っているModも結構多いので、変えなくても大丈夫だと思います。

**Comment by tacigar** [comment]
あ〜, もう変えちゃったんでいいかなという感じです.
GPLv3 にしていた理由も特にないですし...
