### ISSUE TITLE
Wet → Soil への変更

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#122]
何故か `minetest.get_item_group` を 0 or 1 以上の判定に使うことしか考えてなくて, 
`default:dirt` の `group` に `soil = 1` があったので, 土壌の判定には `soil` を使えないと判断していた.

種を植えられる土壌は `soil > 1` で判定すればいいのでそっちを使う.
乾いている状態の土壌でもメイドが種を植えられるようになる.

**Comment by ghost** [comment]
https://github.com/minetest/minetest_game/blob/master/mods/farming/api.lua#L183
farmingのfarming.place_seedにも似たような判定がありますね。
