### ISSUE TITLE
minetest.show_formspec で表示した formspec を on_step で変更する方法が分からない.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#129]
node の場合は `meta:set_string("formspec", ...)` と `on_timer` に書いていれば勝手にやってくれた...

燃料の残量を表す formspec のメータが減っていく処理を書きたいが, むずそう...

**Comment by Rui-Minetest** [comment]
```lua
-- key: プレイヤー名, value: メイドのself
local players = {}

...

minetest.show_formspec(playername, "HOGEHOGE", フォームスペック)
players[player_name] = self

...

-- Formspecの更新処理
minetest.register_globalstep(function()
  for player_name, self in pairs(players) do
    if self then
      ...
      minetest.show_formspec(player_name, "HOGEHOGE", フォームスペック)
    end
  end
end)

minetest.register_on_player_receive_fields(function(player, formname, fields)
  if formname == "HOGEHOGE" then
    if fields.quit then
      players[player:get_player_name()] = nil
    end
  end
end)

minetest.register_on_leaveplayer(function(player)
  players[player:get_player_name()] = nil
end)
```
超重そう😨

**Comment by ghost** [comment]
~~やるとしたらこんな感じかと…。~~
```lua
-- 下に改善した実装があります
```
~~超重そう…😨~~

**Comment by tacigar** [comment]
すごい重そうっw 
考えてくださってありがとうございます！
流石にちょっとヤバいかなという感じではありますけど... 😢

**Comment by ghost** [comment]
show_formspecを実行し続けるのは重過ぎるので、フォームスペックを保存しておいて、変わった時のみ表示を更新するようにすれば、だいぶ軽くなるかもです。

```lua
-- key: プレイヤー名, value: {メイドのself, formspec}
local players = {}

-- Formspecの更新処理
minetest.register_globalstep(function()
  for player_name, data in pairs(players) do
    if data then
      local self, previous_formspec = data[1], data[2]
      if self and self.formspec ~= previous_formspec then
        data[2] = self.formspec -- 更新
        minetest.show_formspec(player_name, "HOGEHOGE", self.formspec)
      end
    end
  end
end)

local function remove_data(player)
  players[player:get_player_name()] = nil
end

minetest.register_on_leaveplayer(remove_data)
minetest.register_on_dieplayer(remove_data)
minetest.register_on_player_receive_fields(function(player, formname, fields)
  if formname ~= "HOGEHOGE" then
    return
  end

  if fields.quit then
    remove_data(player)
  end
end)

…

-- フォームスペックを表示したい時
players[player_name] = {self, self.formspec}
minetest.show_formspec(player_name, "HOGEHOGE", self.formspec)

…

-- self.formspecを変更するだけで表示を更新できます
self.formspec = "..."
```
追記:
この実装だと、0.4.15で追加された[close_formspec](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2339)にはおそらく対応できません。
(close時にon_player_receive_fieldsが呼ばれない、もしくはfieldsにquitが含まれない仕様だった場合は、バグが発生します。)

**Comment by tacigar** [comment]
ありがとうございます！素晴らしいです！
ただ, `show_formspec` のコストがいまいちよくわからないのですが, こんなに step 毎に呼び出しても大丈夫なものなのでしょうか？

> この実装だと、0.4.15で追加されたclose_formspecにはおそらく対応できません。

というのは, Formspec をユーザーが閉じるのを待たないまま, 次の `show_formspec` を呼び出していることが問題なのでしょうか？

**Comment by tacigar** [comment]
動く Formspec がある MOD がないものか... 🤓

**Comment by ghost** [comment]
>ただ, show_formspec のコストがいまいちよくわからないのですが, こんなに step 毎に呼び出しても大丈夫なものなのでしょうか？

show_formspecは重いので、step毎に呼び出すのは良くありません。
そこで、上のコードでは、self.formspecの文字列が変更された時だけ呼び出すようにしています。

>というのは, Formspec をユーザーが閉じるのを待たないまま, 次の show_formspec を呼び出していることが問題なのでしょうか？

playersテーブルの値はフォームスペックを閉じた時に削除されるのが理想なのですが、close_formspecだとon_player_receive_fieldsを実行してくれるかどうかが怪しいので、閉じても削除されない恐れがあります。
(テーブルからの削除はon_player_receive_fieldsで行われます。)

そうなった場合、self.formspecが更新されるとclose_formspecしたプレイヤーに再度フォームスペックが表示されてしまいます。

**Comment by ghost** [comment]
補足
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2344
close_formspecで問題が発生するのはこの呼び出しです。通常の呼び出しの場合は、formnameが必要なので問題ありません。

Ugly Hackですが、こんな対応もできます。
```lua
local close_formspec = minetest.close_formspec
if close_formspec then

  minetest.close_formspec = function(player_name, formname, ...)
    if formname == "" then
      players[player_name] = nil
    end
    return close_formspec(player_name, formname, ...)
  end

end
```

**Comment by tacigar** [comment]
> show_formspecは重いので、step毎に呼び出すのは良くありません。
> そこで、上のコードでは、self.formspecの文字列が変更された時だけ呼び出すようにしています。

すいません, それは分かっています 😓 
`minetest.show_formspec` を連続的に呼び出しても, 表示が途切れ途切れになったりしないのか, という旨のことを書きたかったのですが, 全然そんなことを書けていませんでした... 😢 

> そうなった場合、self.formspecが更新されるとclose_formspecしたプレイヤーに再度フォームスペックが表示されてしまいます。
> close_formspecで問題が発生するのはこの呼び出しです。通常の呼び出しの場合は、formnameが必要なので問題ありません。

なるほど, 意味が分かりました 😄 

> Ugly Hackですが、こんな対応もできます。

うっ... 
この手の対応はちょっと辛い感じはしますね...
特に不具合は起きないとは思いますが...

---

まあ, ちょっと色々辛いなぁという感じなので, 燃料の問題については, とりあえず BBS の方でちゅーはいさんに頂いたアイデアを採用しようと思います.
色々アイデアありがとうございました！

皆さんホント Minetest に詳しすぎて, ヤバいです... 😱

**Comment by ghost** [comment]
>minetest.show_formspec を連続的に呼び出しても, 表示が途切れ途切れになったりしないのか,

大丈夫です。頑張れば動画が再生できるレベルです。

>まあ, ちょっと色々辛いなぁという感じなので, 燃料の問題については, とりあえず BBS の方でちゅーはいさんに頂いたアイデアを採用しようと思います.

良いと思います👍
ちゅーはいさんのように、問題を根本から見直せるようになりたいものです。

>皆さんホント Minetest に詳しすぎて, ヤバいです... 😱

tacigarさんも十分詳しいのでは…。

**Comment by ghost** [comment]
蛇足ですが、Formspecの更新はこうした方がスマートでした…。
備忘録として残しておきます。
```lua
-- key: プレイヤー名, value: inventory_name
local players = {}

local function remove_data(player)
  players[player:get_player_name()] = nil
end

minetest.register_on_leaveplayer(remove_data)
minetest.register_on_dieplayer(remove_data)
minetest.register_on_player_receive_fields(function(player, formname, fields)
  if formname == "HOGEHOGE" and fields.quit then
    remove_data(player)
  end
end)

--------------------
-- フォームスペックを表示したい時
--------------------

players[player_name] = self.inventory_name
minetest.show_formspec(player_name, "HOGEHOGE", self.formspec)

--------------------
-- 表示を更新したいとき
--------------------

local function update_formspec(self, formspec)
  self.formspec = formspec

  for player_name, inventory_name in pairs(players) do
    if inventory_name == self.inventory_name then
      minetest.show_formspec(player_name, "HOGEHOGE", formspec)
    end
  end

end

update_formspec(self, "formspec")

--------------------
-- Formspecを閉じたい時
--------------------

local function close_formspec(self)
  for player_name, inventory_name in pairs(players) do
    if inventory_name == self.inventory_name then
      minetest.show_formspec(player_name, "HOGEHOGE", "")
      remove_data(minetest.get_player_by_name(player_name))
    end
  end
end

close_formspec(self)
```

**Comment by tacigar** [comment]
> 大丈夫です。頑張れば動画が再生できるレベルです。

あ～, Bad Apple のやつはそんな感じでやってたんですね！

> tacigarさんも十分詳しいのでは…。

いえ, 何がどう問題になりそうか, マルチの場合はどうか, という知識が全然ありません...
