### ISSUE TITLE
get_staticdata と on_activate を修正

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#139]
BBS でご指摘いただいた.
以下引用.

> get_staticdata() / on_activate()でデータの保存・復帰を行っている部分で
> インベントリーの保存・復帰の方法に現時点だと以下の問題点があると思います。
> (1) 空のスロットを無視しているので復帰後のインベントリーが整理された状態になる
> (2) add_itemで追加しているので同じアイテムがスタックしてしまう
> (3) wearやmetadataを保存していないのでツールが初期状態になる 
> ですのでnameやcountを個別にテーブルに保存するのではなく、
> 下の例のようにto_string()を使うとmetadataも含めてすべて保存できるのではと思います。

**Comment by tacigar** [comment]
ほほ～, ItemStack ってこんなに賢く使えるのか... 😓

**Comment by ghost** [comment]
mainだけでなくcoreやwieldの方もメタデータを保持するべきなので、以下のようにまとめてもいいかもしれません。
```lua
for list_name, list in pairs(inventory:get_lists()) do
  data["inventory"][list_name] = {}

  for i, item in ipairs(list) do
    data["inventory"][list_name][i] = item:to_string()
  end
end
```

**Comment by ghost** [comment]
ついでに、復帰部分もこうでいいと思います。
```lua
for list_name, list in pairs(data["inventory"]) do
    inventory:set_list(list_name, list)
end
```

**Comment by tacigar** [comment]
`wield_item` と `core` は一つしかないということで, テーブルを避けてたんですが,
確かにその方がまとまっていて良いですね 😄

**Comment by tacigar** [comment]
あ, あと明けましておめでとうございます.

**Comment by ghost** [comment]
明けましておめでとうございます。
本年もよろしくお願いいたします。

**Comment by tacigar** [comment]
> ついでに、復帰部分もこうでいいと思います。

これ, 動くんですね...
一つずつ辿って ItemStack 化しないとダメなのかと思っていました...
勉強になります.

**Comment by tacigar** [comment]
core_name と list とで, 二重にコアの情報を管理している意味が全然分からない.
どういう考えでこういう実装にしたのか...思い出せない...

直すか...
こういうの直すのが一番つらい.

**Comment by Rui-Minetest** [comment]
get_core_nameが忘れ去られてますね…

**Comment by ghost** [comment]
maidroid:dummy_itemのコードを見ていて思ったのですが、wielditemってtextureに`{""}`を指定すれば透明になってくれた気がします。(間違っていたらすみません…)

**Comment by tacigar** [comment]
わお！
そうだったんですね...
最初 "air" を指定していてダメだったんで, ダメなのかぁと思ってました...

**Comment by ghost** [comment]
0.4.13の頃は(おそらく)そうでした。
今通用するかは分からないので、お手数をおかけしますが、確認していただければと思います…。

**Comment by tacigar** [comment]
0.4.15 で試してみたのですが, `textures={""}` では変な物体が表示されてしまいました...
`textures=""`, `textures=nil` では unknown な感じに表示されました.

とりあえず今のままにしておきます... 😢
