### ISSUE TITLE
Improve maidroid's dummy item system.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#145]
New algorithm.
1. `on_activate` of maidroid must creates a dummy item and attach it by `set_attach` every time.
2. The dummy item must be removed in `get_staticdata` every time.

**Comment by tacigar** [comment]
`get_staticdata` が, オブジェクトが消えるタイミングだけじゃなくて, 生成のタイミングでも呼ばれているっぽくてこのままじゃ無理と判明.

**Comment by tacigar** [comment]
dummy_imem が `on_step` で毎回近くの maidroid を探して, ない場合は remove という処理をしているのに倣って, maidroid の `on_step` でも毎回 dummy_item を探し, ない場合は生成するという風にする.
また, dummy_item が複数 maidroid に引っ付かないように, dummy_item の `on_activate` で, チェックする.

**Comment by Rui-Minetest** [comment]
```lua
get_staticdata = function(self)
  return "remove"
end

on_activate = function(self, staticdata)
  if staticdata == "remove" then
    self.object:remove()
    return
  end
end
```
このようにするのはいかがでしょうか。
一瞬出てきてしまうのがネックですが…。

**Comment by tacigar** [comment]
あ〜, `on_activate` → `get_staticdata` という順で呼び出されているんですね...
なので, 一番最初の `on_activate` の時だけは `staticdata` は空文字なので, 消されないと...
素晴らしいです！

**Comment by ghost** [comment]
~~すみません、間違っていたかもしれないので消しました…。~~
やっぱり出来るかもしれません。

```lua
get_staticdata = function(self)
  return "remove"
end

on_activate = function(self, staticdata)
  if staticdata == "remove" then
    self.object:remove()
    return
  end
end
```

**Comment by chu-hai** [comment]
BBSに書いたときは
1. add_entity()を呼び出してエンティティ作成
2. on_activate(), get_staticdata()が呼び出される
3. 制御がadd_entity()の後に戻るので戻り値のobjを経由してエンティティを初期化
4. 消えるときのget_staticdata()では初期化済みならremove()
ってなことをイメージしてました。

**Comment by tacigar** [comment]
なるほど！ありがとうございます

**Comment by tacigar** [comment]
`get_staticdata` で `self.object:remove` を呼び出しても上手く削除されないっぽいっす...
`remove` は一応呼び出されてるっぽいですが, どんどん dummy_item が増えていってしまう...

**Comment by ghost** [comment]
~~~get_activateでフラグを立てて、on_stepで削除するのはどうでしょう。~~~
的外れでした、すみません…。(get_activateとは…)

**Comment by tacigar** [comment]
`get_activate`... どっちだ... 😅

**Comment by ghost** [comment]
混乱している…(笑)
さっきのon_activateで消すコードを使うのはいかがでしょう？動くか確認はしていませんが…。

**Comment by tacigar** [comment]
そうですね...
試したところちゃんと動きました！

**Comment by Rui-Minetest** [comment]
get_staticdataで動かないのって、呼び出しの時点で既にself.objectは削除されているってことなんでしょうかね。

**Comment by chu-hai** [comment]
うちではget_staticdata()でremove()を呼んで消えていますが、バージョンの差異？
ちと見直してみます……

**Comment by tacigar** [comment]
> get_staticdataで動かないのって、呼び出しの時点で既にself.objectは削除されているってことなんでしょうかね。

`remove` 自体は呼び出せるので削除はされてないと思います... ちょっと謎ですね...

> うちではget_staticdata()でremove()を呼んで消えていますが、バージョンの差異？

ほんとですか！
当方 Mac で version 0.4.14 で試しています.

**Comment by chu-hai** [comment]
遠くに行った場合はOKだけど、ログアウト・ログインの場合はダメっぽいですね。
remove()を呼んでも残ってました。

**Comment by tacigar** [comment]
自分の環境では遠くへ行った場合もダメでした... 😢
