### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by tobyplowy** [tacigar/maidroid#155]
@tacigar I Would love to see More customisation for example being able to change there hair [like this](http://images.onesite.com/capcom-unity.com/user/ray_silver/minecraft/large/036305c676d938ae6d7ea2c6944d2de6.png?v=222600) 
Also cloth coloring (there's already difrent maidroid colors) but Actual cloths that work like Armor instead of being part of the entity

Also Being able to change the color of their eyes would be cool

**Comment by tacigar** [comment]
Good 😄 
But I think it takes time to implement this, bacause I need to create new 3d models and their textures 😢 

I'll think about it.

**Comment by tobyplowy** [comment]
@tacigar just emagine how amazing it would be also this mod is crazy your so good!

**Comment by HybridDog** [comment]
You could make the 3d model be able to have everything by simply setting parts of the texture invisible.
