### ISSUE TITLE
Nametagによる名前の変更

### ISSUE THREAD

**Issue by chu-hai** [tacigar/maidroid#163]
現状では`is_named()`でチェックして変更を出来なくしていますが、なにか理由はあるのでしょうか？
軽く試した限りだと

- 変更は普通に可能
- 削除は`set_nametag_attributes()`では不可、`set_properties()`では可能

という感じでした。

**Comment by tacigar** [comment]
元々 maidroid の名前は nametag などを使わなくても, formspec でいつでも自由に書き換えられるようにしていたのですが, 名前を一度しかつけられないようにした理由はおそらくその反動ですね...
コロコロ名前を書き換えられるより, 一度決めた名前は変えられない方が愛着が沸くと判断したんだと思います.
ですが, ぶっちゃけナンセンスですね...変えようと思います.

`set_nametag_attribute` で削除不可ってマジですか...試してみます 😄

**Comment by tacigar** [comment]
うわ...マジですね.
どういう仕様なんだ...
