### ISSUE TITLE
maidroid.maidroid.* という意味のないテーブルの関数

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#165]
どういうつもりでこういう実装にしたのかすら覚えていないが, 何の意味もないのでやめた方が良い.

**Comment by ghost** [comment]
個人的にはエンティティのメソッドと区別しやすくて良いなぁと思っているのですが…。
ただグローバルである必要がなく、親と子のテーブルの名前も被っているので、maidroid_methods的な名前のローカルテーブルにしたほうが良いとは思います。

**Comment by chu-hai** [comment]
初めは外部から呼び出せるAPIとして実装したものをluaentity経由でも実行できるようにした結果
とかでしょうか？
現時点では全てのメソッドがluaentity側から参照できるので、ぶっちゃけlocal functionでも
いいような気もしますね。

ただ、api.luaは将来的に肥大化しそうですし、モジュール分割とかを考えるとグローバルのままでも
悪くないのかも？という気もします。

**Comment by tacigar** [comment]
> 個人的にはエンティティのメソッドと区別しやすくて良いなぁと思っているのですが…。

確かにそういう感じもしていたので放置していたのですが, ちょっとダサいなぁ〜と思い始めまして...

> 初めは外部から呼び出せるAPIとして実装したものをluaentity経由でも実行できるようにした結果
> とかでしょうか？

そういう感じです...
