### ISSUE TITLE
Mod 名を変えたい（切実）

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#167]
辛い...
forum のプライベートメッセージでも変えるべきだと指摘された...

**Comment by ghost** [comment]
Mod名を変えるのって結構面倒ですよね…。
どういった理由で指摘されたのでしょうか？

**Comment by tacigar** [comment]
South Korean Porno と同じ名前という理由です...
気づいてはいたのですが, ちょっと今から変えるのも面倒だなぁと思って放置してました... 
ですが, 改めて指摘されると確かに良くないなぁと思いました...

**Comment by ghost** [comment]
そうですね…😅
Mod名の変更も辛いですが、アレなビデオと被っているのはもっと辛い感じですね…。
私からは"MaidBot"もしくは"MaidBots"を提案しておきます。(注: 前者は同名の企業が存在します)

**Comment by tacigar** [comment]
そうなんですよね...
普通のビデオならいいんですが...

Maidbots いいですね！

**Comment by chu-hai** [comment]
何事かと思ったらそういうことでしたか……
検索してみたら確かにそれらしいものがヒットしましたが、これって
単純にアレなビデオっていうより、どうもコメディ寄りの映画っぽい感じ？
まあ、映画のタイトルと同じというのは著作権的な面でも避けた方が良いと思います。

> Maidbots いいですね！

私もこれが良いかな？と思います。


と言うか……Maidroidもカタカナで書くとクラゲみたいな地球外生命体が出てくる
ゲームの名前っぽいですね。

**Comment by tacigar** [comment]
> まあ、映画のタイトルと同じというのは著作権的な面でも避けた方が良いと思います。

そうですよね...

> と言うか……Maidroidもカタカナで書くとクラゲみたいな地球外生命体が出てくる
> ゲームの名前っぽいですね。

何でしょうか？
分からない... 😅 

ちょっと今 Debian のパッケージに載せてもらってる感じなので, メンテナの人に名前を変えても大丈夫か聞いてから変更しようと思います... 😢

**Comment by ghost** [comment]
>何でしょうか？
>分からない... 😅

https://youtu.be/jrtPqdsvzKk

>ちょっと今 Debian のパッケージに載せてもらってる感じなので, メンテナの人に名前を変えても大丈夫か聞いてから変更しようと思います... 😢

この際パッケージごと譲渡してもらったほうが、管理が楽だと思うのですがどうでしょう…。

**Comment by tacigar** [comment]
あ〜, メトロイド！聞いたことあるような...無いような... 😅 
教えていただいて, ありがとうございます.

> この際パッケージごと譲渡してもらったほうが、管理が楽だと思うのですがどうでしょう…。

可能ならそうしたいですね... 
いまいち Debian や Ubuntu のパッケージの仕組みが分かっていないもので, そういったことが出来るのかどうかわからない... 😅

**Comment by ghost** [comment]
https://www.debian.org/doc/manuals/developers-reference/
メンテナになる方法は見つかりましたが、正直面倒そうですね…。
やっぱ頼むほうが楽かもしれません…。

**Comment by tacigar** [comment]
あ, すいません！調べていただいて！
そうですね...
今度メンテナの方に連絡しようと思います... 😅 
ありがとうございました！
