### ISSUE TITLE
Rename "maidroid" to "maidbots".

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#168]
> Debian は現在リリースをフリーズしているので, unstable 内のパッケージを rename するには一年かかる.
> しかし名前を変えるのは別に OK.

ということらしいです.

まあ, 一年後にはパッケージから外されてるかもしれないし変えることにします.

**Comment by chu-hai** [comment]
> まあ, 一年後にはパッケージから外されてるかもしれないし変えることにします.

まあ、パッケージ名が変わったりするのはapt側で何かしらの対処が出来るでしょうから問題はないと
思います。本来パッケージャが行う範囲の内容ですしね。

ただ、Minetest側のケアは必要になると思います。
エンティティは単純にaliasで対処出来なかった気がしますので……。

**Comment by tacigar** [comment]
> ただ、Minetest側のケアは必要になると思います。
> エンティティは単純にaliasで対処出来なかった気がしますので……。

そうですよね...
今までは互換性とか一切考えずに実装してきましたが, そうはいかなくなってきてしまいました...

**Comment by chu-hai** [comment]
Maidroid自体は既にmodpack形式なので、maidbots_compat的なmodを追加してそこにalias処理等を
放り込んでおけば良いかと。

エンティティに関しても、mobs_redoが単一modからmodpack形式に移行しているので参考になると
思います。

**Comment by tacigar** [comment]
アドバイスありがとうございます！
Minetest の MOD で互換性を考えたことが今まで無かったので（目を背けてきたので）,とても助かります 😄
