### ISSUE TITLE
複数のコアを使用することによるカスタマイズ

### ISSUE THREAD

**Issue by chu-hai** [tacigar/maidroid#169]
現状では、コアは１つだけしか使えませんが、そのため以下のような感じになっています。

- 複数のコアで同じロジックが重複している。
  - 複数のコアに同じロジックがあるのでバグがあった場合、修正が大変。
- 複数のコアの機能が必要な場合、新しくコアを作成する必要がある。
- Basicコアの存在意義が少ない。

と、いうわけで次のような形で複数のコアを搭載出来るようにするのは如何でしょうか？

- コアスロットを複数の拡張用コア＋Basicコア専用の様な形にする。
- 拡張用コアのスロットは優先順位をつけ、上位のコアが処理を行ったら下位のコアの処理は行わない。
(`core.on_step()`の戻り値で判断)
- 全ての拡張用コアで処理を行わなかった場合はBasicコアで処理を行う。
- Basicコアが搭載されていない場合はInactive状態にする。
- 燃料の概念をBasicコアに持たせるのも有り？

例えば、

- アイテムを拾いにいくコア
- 敵を攻撃するコア
- 松明を設置するコア

この３つのコアを並び替えることでメイドさんの動作の優先順位がカスタマイズ出来るかな？
と思います。

**Comment by tacigar** [comment]
すいません. Issue 気づいてませんでした 😞 .
すごい面白いというか, ユーザビリティが上がりそうなアイデアですね...
ちょっと考えておきます！
