### ISSUE TITLE
Crash using the egg writer

### ISSUE THREAD

**Issue by bell07** [tacigar/maidroid#173]
I tried the mod and get the game crashed as I tried to get the written egg to the inventory.
`2018-01-05 09:58:08: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'maidroid_tool' in callback nodemeta_inventory_OnTake(): ...ods/maidroid/maidroid_tool/egg_writer.lua:165: attempt to index local 'egg_entity' (a nil value)`

By the way, in debug.txt I see the message 
`Undeclared global variable "pdisc" accessed at ...game/mods/maidroid/maidroid_core/init.lua:16` 
at init that should not be happen.

**Comment by ghost** [comment]
https://github.com/tacigar/maidroid/blob/master/maidroid_core/init.lua#L16
-> if minetest.global_exists("pdisc") then

https://github.com/tacigar/maidroid/blob/master/maidroid_tool/egg_writer.lua#L165
There is no "nil check"...

**Comment by ghost** [comment]
#174, #175
