### ISSUE TITLE
Maidroidに名前を付ける機能

### ISSUE THREAD

**Issue by ghost** [tacigar/maidroid#33]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3473
タイトルの通り。
名前が付けられれば個体の判別が容易になると思います。

**Comment by tacigar** [comment]
@Rui-Minetest  nametagは結構気になっていてそういう機能も実装したいと思っていたのですが、
maidroid自体の生成方法がまだ決まっていなくて、どうしたものかなぁという感じです…。

**Comment by ghost** [comment]
maidroid_toolで名前を付けるためのアイテム(名札など)を提供するのはどうでしょうか。
MaidroidのGUIから… とも考えましたが実装が難しそうですね…。

**Comment by tacigar** [comment]
MaidroidのGUIから名前を設定できるようにしてみました。
ちょっとマージするのは憚られるコードの出来ですが、一応動きます。
#36
