### ISSUE TITLE
Maidroidの状態をinfotextで表示する

### ISSUE THREAD

**Issue by ghost** [tacigar/maidroid#34]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3475
稼働/待機 の状態がinfotextで見えるようになれば便利だと思います。
入っているcoreの名前や状態も見られれば更に良さそうですが、さすがに実装が面倒そうですね…

**Comment by tacigar** [comment]
アイデアありがとうございます！
#35 こんな感じになりましたが、どうでしょうか

![maidroid_infotext](https://cloud.githubusercontent.com/assets/19551419/18587997/8786043e-7c5f-11e6-8436-5bb16efddb5a.PNG)

**Comment by tacigar** [comment]
もうちょっと格好いい感じに出力できればなぁとは思うのですが…。

**Comment by ghost** [comment]
良いですね！

> もうちょっと格好いい感じに出力できればなぁとは思うのですが…。

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1785
色を付けるのはどうでしょう。

**Comment by tacigar** [comment]
`core.colorize`が`core`テーブルに見当たらないです…。
バージョンが違うのでしょうかね

**Comment by ghost** [comment]
あ… 0.4.14リリースの後に追加された機能でした… 申し訳ありません。

**Comment by tacigar** [comment]
いやいや。
ですが、今回は`core.colorize`は使わないことにしておきます。
情報ありがとうございました！
