### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#48]
- [x] maidroidにアイテムを持たせる機構の開発
    + [x] formspecの変更
    + [x] APIの開発
        * [x] wieldのスタックを取得するAPI
        * [x] mainからwieldにアイテムを移動させるAPI
    + [x] 持っているアイテムを手に持たせる機構
- [ ] Farming coreの作成
- [ ] Lumberjack coreの作成
- [ ] maidroid生成ノードの作成
- [ ] ここまでの機能をテスト
- [ ] README記述
- [ ] テスト
- [ ] v0.1リリース

---
- [ ] Guard coreの作成
- [ ] 防具をmaidroidに着せる方法（可能なのか？）

**Comment by ghost** [comment]
> 防具をmaidroidに着せる方法

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2788
settexturemodで防具のテクスチャを被せればそれらしくなると思います。

**Comment by tacigar** [comment]
それ用のAPIも提供されているんですね！
情報ありがとうございます。
