### ISSUE TITLE
Farming Core を作成する.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#57]
農業用の Core , Farming Core を作成する.  
Version 0.4.13 以前の `minetest.find_path` は `air` 以外のノードを避ける様に作られているため, 少なくとも農業用のモジュールには使えない ( 稲を一々避けてたら不自然である ) .  
したがって, 経路探索は自前で実装することとする.

**Comment by tacigar** [comment]
自前で A* アルゴリズムを実装するべきか, もっと軽い適当なもので実装するべきかは要検討.

A* で実装するメリットとしては以下のものが上げられる.

- maidroid の動きが正確になる（障害物のある方向へは向かわなくなる）.

デメリットとしては, 以下のものが上げられる.

- 単純に実装がしんどい. 平面の話なら良いが, 3次元で考えると面倒臭そう（想像）.
- 結構リッチなアルゴリズムなので, 呼び出されるタイミングや範囲などを工夫しないと重くなりすぎる.

まあ, 当面は軽い実装でやっておいて, できそうなら A* に移行するのもありか.

**Comment by ghost** [comment]
`minetest.find_path`の使用について切替設定を設けるのはいかがでしょう。
[settingtypes.txt](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L166)を使用すれば、Modの設定を詳細設定メニューに表示することができます。

(かなり泥臭いですが、`minetest.get_color_escape_sequence`の有無で0.4.14以上かどうかを判定するという方法もあります。)

**Comment by ghost** [comment]
> 結構リッチなアルゴリズムなので, 呼び出されるタイミングや範囲などを工夫しないと重くなりすぎる.

coroutineを使うのはいかがでしょう。

**Comment by tacigar** [comment]
@Rui-Minetest 
ぶっちゃけ今の所, Debian のパッケージの Minetest のバージョンにしか関心はないので, 0.4.14 以降に関してはとりあえず考えないようにしておきます.

> (かなり泥臭いですが、minetest.get_color_escape_sequenceの有無で0.4.14以上かどうかを判定するという方法もあります。)

めちゃくちゃ泥臭いですね...
この方法をとってバージョンを判定している MOD ってあったりするんでしょうか...？

> coroutineを使うのはいかがでしょう。

辛そう...

**Comment by tacigar** [comment]
Lumberjack に関してもだが, 状態遷移を含むコードが散らかりすぎ.
ある程度は仕方がないが, もう少し工夫できる部分はあると思われる.

- `on_step` のケツでは絶対に `preposition` の更新処理が必要.
- `on_step` のケツでは絶対に `time_counter` の更新が行われるが, `0` or インクリメントは場合による.
- 状態遷移の時に更新する必要のあるものは限られている.
    + `state`
    + `destination`
    + アニメーション
    + 向き
    + 速度

**Comment by ghost** [comment]
> この方法をとってバージョンを判定している MOD ってあったりするんでしょうか...？

ありません。誰もこんな方法取りたくないでしょう(笑)

> coroutine 辛そう...

そんなに辛くないかもです…？

https://gist.github.com/Rui-Minetest/5b5387366bab56d69d9ba52dd9f2ebd6
私が思い描いているのはこんな感じですね。
経路探索アルゴリズムはよく知らないので、上の方の実装は当てになりませんが、coroutineの雰囲気だけ感じ取っていただければ…。

**Comment by tacigar** [comment]
@Rui-Minetest 
ありがとうございます！
Lua に限らず, コルーチン系をほとんど触ったことがないので, 実装が全然想像できなかったんですが, それほど複雑にはならない感じですね！
`yield` のタイミングが一番想像できなかったんですが, なるほど！という感じでした.

ただ #77 みたいな感じなので, とりあえずは 0.4.14 をターゲットにして実装してもいいかなと思ったりもしています...

**Comment by ghost** [comment]
resumeの最初の返り値はスレッドが死んだかどうかが返されるそうなので、
```lua
-- こうではなく、
local success, path = coroutine.resume(self.pathfinding_thread)
-- こうでした。
local _, success, path = coroutine.resume(self.pathfinding_thread)
```
すみません…。

> とりあえずは 0.4.14 をターゲットにして実装してもいいかなと思ったりもしています...

やったー。Ubuntu系なら[公式リポジトリ](https://launchpad.net/~minetestdevs/+archive/ubuntu/stable)があるので、それに合わせてもいいかもしれません。

**Comment by tacigar** [comment]
もしかしたら, A* アルゴリズムの実装を考えてくださってたのかなぁと思っていて...
もしそうなら申し訳ないです... :disappointed_relieved:

> Ubuntu系なら公式リポジトリがあるので、それに合わせてもいいかもしれません。

あ〜, それもありですね...

**Comment by ghost** [comment]
>もしかしたら, A* アルゴリズムの実装を考えてくださってたのかなぁと思っていて...
もしそうなら申し訳ないです... 😥

大丈夫です、単に書いてみたかっただけなので…(書けたとは言わない)。
実際に動くかどうか分かりませんし、使うこと自体を想定していません(笑)

そういえば、`find_path`で得られる経路を実際に歩かせるための実装ってもう考えてあるのでしょうか…？
これ、結構面倒で難しい気がします…。

**Comment by tacigar** [comment]
> これ、結構面倒で難しい気がします…。

まだ `find_path` を全然さわれていないので, よくわかっていないのですが, どこらへんが難しそうですか？

**Comment by ghost** [comment]
まず、`find_path`は、目標までの経路を座標のリストとして返します。
それを元にメイドちゃんがする(べき)動作は
```
1. リスト先頭の座標まで移動
2. 移動できたらtable.removeでリスト先頭を削除
3. 1に戻る もしリストの中身が全て無くなっていればここで終了
```
です。

これだけならまだ楽なのですが、一度取得した経路をそのまま保持する場合、マップの変化に対応できないという問題が発生します。そのため、移動で引っかかるか一定時間経ったら経路を再取得する、といった対処が必要になります。(後者の方が実装しやすいと思います)
また、常に経路を取得し先頭の座標のみに向かう、という方法もあるのですが、重いしエラーメッセージも出やすいのでお勧めしません。


まあ、つまりは、正しく進ませることよりも、正しく進めない場合の対処が面倒ってことですね…。
あと、綺麗なコードを保つのも難しいです。

なぜか最近AI APIのModが増えているみたいなので、そちらも参考にすると良いと思います。
Mobs Redoも`find_path`に対応していたと思います。
https://forum.minetest.net/viewtopic.php?t=15572
https://forum.minetest.net/viewtopic.php?t=16032
https://forum.minetest.net/viewtopic.php?t=16083

**Comment by tacigar** [comment]
あ〜なるほど, マップの変化については考えてなかったです...
確かに一定時間毎に経路の再計算をするというのが一番良さそう（簡単そう）ですね.

> なぜか最近AI APIのModが増えているみたいなので、そちらも参考にすると良いと思います。

増えてるんですね...
リンク貼ってくださってありがとうございます.
参考にさせていただきます.

**Comment by tacigar** [comment]
柵だけは飛び越さないという仕様にしようと思う.
