### ISSUE TITLE
Maidroid ai Improvement

### ISSUE THREAD

**Issue by tobyplowy** [tacigar/maidroid#6]
For some reason if you get a lumberjack maidroid they just get some random trees ( I think they should go for the closest tree to them) because now making a farm is pretty much impossible they just try to find a tree somewhere like a hundred blocks away even though there's a treat just next to them ( it's really annoying)

**Comment by tacigar** [comment]
If I do so with the current algorithm, the searching process become very heavy :-(

If you want to do so, please change the following code 
`local find_lenvec = {x = 3, y = 0, z = 3}`
to
`local find_lenvec = {x = 15, y = 0, z = 15}`

**Comment by tobyplowy** [comment]
@tacigar thank you
