### ISSUE TITLE
trees don't get destroyed completely

### ISSUE THREAD

**Issue by tobyplowy** [tacigar/maidroid#7]
@tacigar trees don't get destroyed completely 
![fuuuuuuu](https://cloud.githubusercontent.com/assets/16853304/16048170/512e15c6-3253-11e6-8112-e4dc5305f576.png)

**Comment by tobyplowy** [comment]
@tacigar Don't look at the red little circle in the first screenshot that's a mistake I made and I'm too lazy to fix it :)

**Comment by tacigar** [comment]
Now, this mod supports "default:tree", which is upright and doesn't have branchs, so maidroids cannot punch branchs :-(
But I think that it is not useful, I will think about it.

Thank you for your comments .

**Comment by tobyplowy** [comment]
@tacigar this tree is from the default game :)

**Comment by HybridDog** [comment]
It's not part of mgv6, is it?

**Comment by tacigar** [comment]
@HybridDog
Ohh I see! 
mgv7!
I have only thought about mgv6 :(

**Comment by HybridDog** [comment]
The maidroid could scan the whole tree(chunk) and remove every trunk in it beginning from the bottom.

Where are the modules now?

When l thought about the effects of using a photo of my mother as skin for the maidroid, l noticed that cutting trees is officially something men prefer doing, so how about giving the maidroid special wigs for some jobs?

**Comment by tacigar** [comment]
@HybridDog

> The maidroid could scan the whole tree(chunk) and remove every trunk in it beginning from the bottom.

Thank you for your idea !

> Where are the modules now?

Sorry, I am rewriting the code, so now lumberjack module and farming module cannot be used.
Please checkout to `7887bc7b958a6c04bda53abeb7df7e8d88a0d542`.

> how about giving the maidroid special wigs for some jobs?

Thank you for your idea.
I want to make other maidroid that has a different hair style.
