### ISSUE TITLE
Maidroid の種類を増やす.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#75]
染料との関係を考えて色を決定し, Maidroid を増やす.

**Comment by tacigar** [comment]
モデル自体は同じものをとりあえず使い回す.
ので, テクスチャのみで違いを表現する.
適当に自動生成のスクリプトを書く.

**Comment by tacigar** [comment]
![screenshot_20161220_212728](https://cloud.githubusercontent.com/assets/19551419/21350597/78fb2994-c6fb-11e6-8fff-9891250f9a38.png)
こんな感じにします.

**Comment by ghost** [comment]
かわいい…！

**Comment by tacigar** [comment]
ありがとうございます！
