### ISSUE TITLE
Dummy item が消えてない.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#86]
よくよく考えれば, その処理を入れてなかったから当たり前.
`set_attach` してれば勝手に一緒に消えると勘違いしていた.
Maidroid が消える時に, 一緒に Dummy item も消す必要がある.
LuaEntity にはそのためのコールバックが無いっぽいので, 他の方法を探す必要がある.

**Comment by tacigar** [comment]
maidroid の `on_punch` コールバックで `get_hp()` で体力を得て, マイナスになっていた場合は, Dummy item を削除するという方針で大丈夫だろうか.
落下時のダメージとかを考えるのであれば, その場所でも同じ処理が必要.

**Comment by ghost** [comment]
Dummy item側で、attachされていないか近くにメイドが居ないときは勝手に消えるように実装する方が良いと思います。

**Comment by tacigar** [comment]
全くその通りですね...
ありがとうございます！
