### ISSUE TITLE
Egg と Maidroid のテクスチャについて.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#89]
今は imagemagick を使った生成スクリプトを用いて, 事前にテクスチャを作成しているが, Minetest 内でも生成することが出来そうな雰囲気.

**Comment by tacigar** [comment]
これは, まあとりあえずいいか...

**Comment by ghost** [comment]
`"maidroid_empty_egg.png^(maidroid_egg_design_base.png^[colorize:color)"`
Minetest内で実装するならこんな感じでしょうか。`maidroid_egg_design_base.png`は卵の模様のテクスチャです。
