### ISSUE TITLE
Maidroid holding tools

### ISSUE THREAD

**Issue by tobyplowy** [tacigar/maidroid#9]
It would be awesome if the Maidroid used actual tools for example the farmer could hold a hoe and The Lumberjack could hold a axe ( if you didn't understand that I'm basically asking for them to hold tools in their hand)

**Comment by tacigar** [comment]
Great idea.

**Comment by tacigar** [comment]
![maidroid_wield_item](https://cloud.githubusercontent.com/assets/19551419/18543801/987faa7c-7b6c-11e6-9c35-c37559cb9201.gif)

Probably, I can implements it.

**Comment by tobyplowy** [comment]
@tacigar this is awesome! I was kind of scared this mod was dead, Thank You For all the hard work This is my favorite mod :)

**Comment by tobyplowy** [comment]
@tacigar Maybe another idea I have is if you give them better tools they work faster like they start off with wooden tools and you can give Them iron or Diamond tools to make Them work Faster (with bad tools they break blocks slower)

**Comment by tacigar** [comment]
Sorry, I have been busy for other works, so I could not implement maidroid mod.

That sounds like a good idea.
I will try to implement it :)

**Comment by tobyplowy** [comment]
@tacigar I just want to say that I really appreciate your work! And that your mod is my absolute favorite Of All minetest mods

**Comment by tacigar** [comment]
@tobyplowy Thanks! I'm glad to hear you say that.
