### ISSUE TITLE
Maidroid のサイズを変更したい.

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#95]
Player と横に並ぶとよく分かるが, 顔がデカすぎる.
ので, 全体的にサイズを小さくする.

Entity の登録で, 以下のようにすればよい.

```lua
visual_size                  = {x = 6, y = 6},
collisionbox                 = {-0.25, -0.3, -0.25, 0.25, 1.05, 0.25},
```

**Comment by tacigar** [comment]
![maidroids](https://cloud.githubusercontent.com/assets/19551419/21443439/8b7bc5d0-c8e8-11e6-9e55-813d0548e276.PNG)
凄くデカい.

**Comment by ghost** [comment]
bigMaidMob…
本家ではプレイヤーの肩の高さくらいですね。

**Comment by tacigar** [comment]
bigMaidMob ... 可愛くない...笑
調整します！
